### ISSUE TITLE
Danh sách yêu cầu của khách hàng

### ISSUE THREAD

**Issue by hoangnam1201** [hoangnam1201/ProjectCNPM_T7#1]
Triển khai lấy yêu cầu khách hàng (giả sử mình là khách hàng)

**Comment by lamtvu** [comment]
1. Giao diện đẹp, dễ sử dụng( Giao diện trực quan dễ nhìn, thân thiện người dùng)
2. Đăng nhập, đăng ký( Xác minh danh tính thực hiện các chức năng)
3. Tra cứu thông tin chuyến xe( Tìm kiếm chuyến xe dựa trên điểm đến, điểm xuất phát, giá tiền)
4. Hiển thị lộ trình chuyến xe( Cung cấp lộ trình chuyến xe và vị trí hiện tại)
5. Cần có thời gian cụ thể mỗi chuyến( Xác định đúng thời gian để bắt xe)
6. Tìm trạm xe( Xác định trạm xe theo vị trí)
7. Xác thực OTP( Gửi mã xác thực khi đăng ký và lấy lại mật khẩu)
