### ISSUE TITLE
Vẽ lược đồ trạng thái các object

### ISSUE THREAD

**Issue by hoangnam1201** [hoangnam1201/ProjectCNPM_T7#12]

**Comment by derrickvo72** [comment]
Lược đồ trạng thái:
https://drive.google.com/file/d/14tLxAXA0sTxKB7ytAOUkIVgoDbLETaha/view?usp=sharing

**Comment by ducvp72** [comment]
Lược đồ trạng thái Object : 
https://drive.google.com/file/d/1cbE9EFHLm24Eh-qmpLnVc_JSyMivzBVD/view?usp=sharing
