### ISSUE TITLE
Thiết kế và tạo Cơ sở dữ liệu cho project.

### ISSUE THREAD

**Issue by timothytnm26** [hoangnam1201/ProjectCNPM_T7#13]
Dựa vào Requirement Document và các diagrams đã vẽ để thiết kế và tạo cơ sở dữ liệu cho App Phương tiện công cộng.

_Lần chia task đầu tiên nên mình chưa biết rõ về mọi người, mọi người tự vào nhận task nhé !_ 
@hoangnam1201 @lamtvu @derrickvo72

**Comment by lamtvu** [comment]
thiết kế
![image](https://user-images.githubusercontent.com/56057693/114830731-b8a0e580-9df6-11eb-9239-f511aa51a6b0.png)

**Comment by timothytnm26** [comment]
Mình đã xem ERD của các bạn, các bạn có muốn mở rộng Project của mình cho phương tiện khác không, như Tàu lửa, Máy bay,... @lamtvu

**Comment by hoangnam1201** [comment]
@timomint bữa có hỏi thầy rồi, xe bus không là đủ rồi. Mở rộng hơn nữa làm không kịp!

**Comment by timothytnm26** [comment]
ok bạn @hoangnam1201
