### ISSUE TITLE
Tạo Trang chủ và chức năng Đăng nhập, Đăng ký tài khoản.

### ISSUE THREAD

**Issue by timothytnm26** [hoangnam1201/ProjectCNPM_T7#14]
- Tạo trang chủ cơ bản cho App, chưa cần chi tiết các chức năng.
- Tạo trang Đăng nhập, Đăng ký và Sử lý chức năng Đăng nhập, Đăng ký với Database

@hoangnam1201 @lamtvu @derrickvo72

**Comment by ducvp72** [comment]
Đã tạo giao diện Login và Sign Up : 
https://drive.google.com/file/d/1VM9gkyWK4SlRsNdq2ZVoSkgxn_0f4rIt/view?usp=sharing

**Comment by timothytnm26** [comment]
- Giao diện OK.
- Chưa xử lý và ràng buộc input cho Login, Sign Up.
- Theo kế hoạch, các bạn có thêm 1 tuần để hoàn thiện 2 task này, bao gồm cả việc truy vấn Cơ sở dữ liệu và Thêm các Button chức năng cho trang HomePage.

Chúc các bạn một tuần học tập tốt !!

**Comment by ducvp72** [comment]
Đã xong naviagation bar và up lên git hub, pull về mới làm nha các bạn
