### ISSUE TITLE
Xác định yêu cầu của ứng dụng (yêu cầu chức năng)

### ISSUE THREAD

**Issue by hoangnam1201** [hoangnam1201/ProjectCNPM_T7#2]
Triển khai xác định yêu cầu chức năng của ứng dụng

**Comment by lamtvu** [comment]
Yêu cầu hệ thống:
- Hệ thống sẽ gửi mã OTP mỗi khi đăng ký
- Hệ thống sẽ không cho đăng nhập với các tài khoản chưa xác minh OTP và bắt xác minh lại
- Cập nhật vị trí (thời gian) đến trạm của mỗi xe
- Hệ thống hiển thị vị trí, lộ trình trên bản đồ

**Comment by hoangnam1201** [comment]
Yêu cầu chức năng (user):
+ Đăng ký tài khoản
+ Đăng nhập
+ Tra cứu địa điểm trạm xe
+ Định vị vị trí hiện tại
+ Tìm đường
+ Hiển thị các tuyến xe bus chạy qua trạm
+ Tìm kiếm trạm, tuyến xe,...

**Comment by hoangnam1201** [comment]
<Nhóm trưởng>
@lamtvu nếu không có thay đổi gì thì mình chốt các chức năng.
