### ISSUE TITLE
Xác định yêu cầu ứng dụng (yêu cầu phi chức năng)

### ISSUE THREAD

**Issue by hoangnam1201** [hoangnam1201/ProjectCNPM_T7#3]
Các yêu cầu phi chức năng của ứng dụng

**Comment by ducvp72** [comment]
Yêu cầu phi chức năng:
- Ứng dụng phải đảm bảo cập nhật các chuyến xe ngay khi có sự thay đổi  về  hoạt động, thời gian, hướng di chuyển.
- Các chuyến xe phải luôn sẵn sàng để đón đưa khách.
- Đảm bảo độ tin cậy dịch vụ cao cho khách hàng.
- Dữ liệu các chuyến xe, các tuyến, thời gian đón đưa, số lượng khách mỗi chuyến phải được bảo toàn.
- Đảm bảo yêu cầu bật định vị mỗi khi sử dụng ứng dụng dịch vụ.
- Độ sai lệch về tính toán thời gian di chuyển phải được hạn chế mức thấp nhất có thể.
- Tương thích tốt với mọi loại màn hình điện thoại.
- Nếu có sự thay đổi đột ngột về thời gian và chuyến xe phải thông báo ngay cho các khách hàng đang đợi chuyến.
- Khả năng bảo trì tốt.
- Khả năng xử lí các xung đột khi số lượng người dùng quá tải đang truy cập ở thời gian xác định.
- Đảm bảo thông tin người dùng được bảo mật tuyệt đối.
- Các dịch vụ của ứng dụng luôn sẵn sàng để khách hàng sử dụng.
- Đảm bảo phản hồi các đánh giá ,yêu cầu, tư vấn từ khách hàng. 
- Khi thay đổi mật khẩu , không được sử dụng lại mật khẩu trước đó.
- Khả năng xử lí đinh vị vị trí nhanh chóng và chính xác.
- Giao diện, chức năng dễ nhìn, dễ sử dụng thích hợp mọi lứa tuổi.
- Ứng dụng cần đạt được số lượng người sử dụng nhất định.

**Comment by hoangnam1201** [comment]
<Nhóm trưởng>
@derrickvo72 có một số chức năng khó có thể đạt được như:
- Đảm bảo phản hồi các đánh giá ,yêu cầu, tư vấn từ khách hàng.
- Nếu có sự thay đổi đột ngột về thời gian và chuyến xe phải thông báo ngay cho các khách hàng đang đợi chuyến.
- Các chuyến xe phải luôn sẵn sàng để đón đưa khách.
