### ISSUE TITLE
Đặc tả yêu cầu phần mềm (Ngôn ngữ có cấu trúc)

### ISSUE THREAD

**Issue by hoangnam1201** [hoangnam1201/ProjectCNPM_T7#5]
Đặc tả yêu cầu phần mềm theo 3 cách: ngôn ngữ có cấu trúc, bảng, sơ đồ usecase

**Comment by lamtvu** [comment]
https://drive.google.com/file/d/1AcB6IpqRCDLc8l2XKbyd8D_lkpF-FXlo/view?usp=sharing

**Comment by hoangnam1201** [comment]
Đã xem
