### ISSUE TITLE
Đặc tả yêu cầu phần mềm (Vẽ sơ đồ usecase)

### ISSUE THREAD

**Issue by hoangnam1201** [hoangnam1201/ProjectCNPM_T7#6]
Vẽ sơ đồ usecase cho các chức năng chính

**Comment by derrickvo72** [comment]
Đặc tả yêu cầu phần mềm: 
https://drive.google.com/file/d/1tJKVffSJIkxAcn3D9kzfsOBN7Ht45Txe/view?usp=sharing

**Comment by ducvp72** [comment]
Đặc tả yêu cầu phần mềm:

https://drive.google.com/file/d/1_87Wnmtx7vAEaTiGg21ArS1KiE_Gl5UO/view?usp=sharing

**Comment by hoangnam1201** [comment]
@derrickvo72  không xem được file

**Comment by ducvp72** [comment]
Cập nhật link mới  :
 https://drive.google.com/file/d/1_87Wnmtx7vAEaTiGg21ArS1KiE_Gl5UO/view?usp=sharing
