### ISSUE TITLE
Thiết kế lược đồ UseCase và mô tả (các chức năng chính)

### ISSUE THREAD

**Issue by hoangnam1201** [hoangnam1201/ProjectCNPM_T7#7]

**Comment by derrickvo72** [comment]
Usercase: 

https://drive.google.com/file/d/1LpTq0FJs85rOOW3hWmoDesJPwF_qZTDZ/view?usp=sharing

**Comment by ducvp72** [comment]
Usecase và mô tả:
https://drive.google.com/file/d/11mI4CqW_CX4pPj4hzmrO-BGMqfeg_1OL/view?usp=sharing
